export function generateRandomString(length: number = 8): string {
  const chars = 'abcdefghijklmnopqrstuvwxyz0123456789';
  let result = '';
  for (let i = 0; i < length; i++) {
    result += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return result;
}

export function generateTestUser(role: string = 'user') {
  const rnd = generateRandomString(6);
  return {
    username: `testuser_${rnd}`,
    email: `testuser_${rnd}@example.com`,
    password: `P@ssw0rd_${rnd}`,
    mobile: `9999${Math.floor(100000 + Math.random() * 900000)}`,
    roles: [role],
    user_type: 'employee',
    organization_id: `playwright-org-${rnd}`
  };
}

export function generateTestForm() {
  const rnd = generateRandomString(6);
  return {
    title: `Test Form ${rnd}`,
    slug: `test-form-${rnd}`,
    description: "Generated by Playwright",
    is_public: false,
    schema: {
      type: "object",
      required: ["full_name", "email"],
      properties: {
        full_name: { type: "string", title: "Full Name" },
        email: { type: "string", format: "email", title: "Email" },
        age: { type: "number", title: "Age" },
        feedback: { type: "string", title: "Feedback" }
      }
    }
  };
}

export function generateTestResponse(formData: any = {}) {
  return {
    data: {
      full_name: `Test User ${generateRandomString(4)}`,
      email: `test_${generateRandomString(4)}@example.com`,
      age: Math.floor(Math.random() * 50) + 18,
      feedback: "This is a test response generated by Playwright."
    },
    ...formData
  };
}

export function generateTestWorkflow(formId: string) {
  const rnd = generateRandomString(6);
  return {
    name: `Workflow ${rnd}`,
    description: `Workflow for form ${formId}`,
    trigger_form_id: formId,
    steps: [
      {
        step_name: "Initial Review",
        order: 1,
        concurrency_type: "serial",
        approvers: [], // Will be filled with actual user IDs in test if needed
        required_approvals: 1
      },
      {
        step_name: "Final Approval",
        order: 2,
        concurrency_type: "serial",
        approvers: [],
        required_approvals: 1
      }
    ]
  };
}
