export function generateRandomString(length: number = 8): string {
  return Math.random().toString(36).substring(2, 2 + length);
}

export function generateTestUser(role: string = 'user') {
  const rnd = generateRandomString(6);
  return {
    username: `testuser_${rnd}`,
    email: `testuser_${rnd}@example.com`,
    password: `P@ssw0rd_${rnd}`,
    mobile: `9999${Math.floor(100000 + Math.random() * 900000)}`,
    roles: [role],
    user_type: 'employee',
    organization_id: `playwright-org-${rnd}`
  };
}

export function generateTestForm() {
  const rnd = generateRandomString(6);
  return {
    title: `Test Form ${rnd}`,
    slug: `test-form-${rnd}`,
    description: "Generated by Playwright",
    is_public: false
  };
}
