### model
model_name_or_path: Qwen/Qwen3-30B-A3B-Instruct-2507
template: qwen3
trust_remote_code: true
quantization_method: bnb
quantization_bit: 4
quantization_type: nf4
double_quantization: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 32
lora_alpha: 64
lora_dropout: 0.05

### dataset
dataset: ridp_train
dataset_dir: lora/data
cutoff_len: 4096
packing: false
preprocessing_num_workers: 8
overwrite_cache: true
val_size: 0.05

### output
output_dir: lora/llama-factory-output
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 0.0002
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_steps: 0
logging_steps: 20
save_steps: 200
save_total_limit: 3
bf16: true
flash_attn: auto

### eval
do_eval: false
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 100

### generation
predict_with_generate: false
max_new_tokens: 256
